### ISSUE TITLE
Redux 4.0 support

### ISSUE THREAD

**Issue by ghost** [josepot/react-redux-scroll#10]
[Redux 4.0 was released in April](https://github.com/reduxjs/redux/releases/tag/v4.0.0).

As it isn't listed in the package.json, a warning is issued during npm/yarn install.

4.0 doesn't have any API changes, so it seems to work without issue in my project so far. It might be just updating the package.json.

**Comment by jwbrady** [comment]
Hmm... I thought it was suppose to delete old Issues? Guess it makes sense it doesn't.

Anyway, yes that was an accidentally created account. That's why I just got rid of it. :)

**Comment by josepot** [comment]
Hi @jwbrady thanks a lot for reporting this!

In the next few days I will publish a new version with a few improvements, among them:

- add tests
- use rollup
- improve docs
- reduce the size of the library

I will make sure that I also update the `peerDependencies`.

Thanks again!
