### ISSUE TITLE
Update for React v15.5.0

### ISSUE THREAD

**Issue by jwbrady** [josepot/react-redux-scroll#5]
`React.PropTypes` has been deprecated and separated into it's own package `prop-types` as detailed [here](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html).

When using `react-redux-scroll`, we get warnings without this being fixed.

I have made a pull request to fix this. #4

**Comment by josepot** [comment]
Hi @jwbrady !

Thanks for reporting the issue and for sending the PR. Sorry that it took me a while to get back to you on this... I've been traveling these days.

Looking into it right now.

**Comment by josepot** [comment]
Hi @jwbrady,

I've merged your PR and I've added another commit so that I can publish a new npm version.

The new version "0.0.10" includes your changes.

Thanks a lot for your contribution!
